#!/usr/bin/env bash
#
# Load profile specific stuff

# Load python manager
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
pyenv activate skennedy
