#!/usr/bin/env bash
#
# Load profile specific stuff

# Load python manager
if which pyenv >/dev/null; then
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
fi
if which pyenv-virtualenv-init >/dev/null; then
    eval "$(pyenv virtualenv-init - zsh)"
fi

pyenv activate skennedy

# Load kubectl auto-completion
command kubectl >/dev/null && source <(kubectl completion zsh)
